export const order = {
  id: 1088,
  parent_id: 0,
  status: "pending",
  currency: "RON",
  version: "7.1.0",
  prices_include_tax: false,
  date_created: "2022-11-27T01:31:05",
  date_modified: "2022-11-27T01:31:05",
  discount_total: "0.00",
  discount_tax: "0.00",
  shipping_total: "0.00",
  shipping_tax: "0.00",
  cart_tax: "0.00",
  total: "109.99",
  total_tax: "0.00",
  customer_id: 0,
  order_key: "wc_order_TlgAa4q9PlWcW",
  billing: {
    first_name: "Test",
    last_name: "Test",
    company: "",
    address_1: "Calea marasesti nr.157",
    address_2: "",
    city: "Bacau",
    state: "Ro",
    postcode: "",
    country: "Romania",
    email: "vinagapetru11@gmail.com",
    phone: "+40 771775373",
  },
  shipping: {
    first_name: "Test",
    last_name: "Test",
    company: "",
    address_1: "Calea marasesti nr.157",
    address_2: "",
    city: "Bacau",
    state: "Ro",
    postcode: "",
    country: "Romania",
    phone: "+40 771775373",
  },
  payment_method: "cod",
  payment_method_title: "Numerar la livrare",
  transaction_id: "",
  customer_ip_address: "",
  customer_user_agent: "",
  created_via: "rest-api",
  customer_note: "",
  date_completed: null,
  date_paid: null,
  cart_hash: "",
  number: "1088",
  meta_data: [],
  line_items: [
    {
      id: 185,
      name: "Set cadou Jesou de tip gentuță cu ceas, pix și portofel",
      product_id: 982,
      variation_id: 0,
      quantity: 1,
      tax_class: "",
      subtotal: "109.99",
      subtotal_tax: "0.00",
      total: "109.99",
      total_tax: "0.00",
      taxes: [],
      meta_data: [],
      sku: "",
      price: 109.99,
      image: {
        id: "991",
        src: "https://development.cadouribarbati.ro/wp-content/uploads/2022/11/image00016.jpeg",
      },
      parent_name: null,
    },
  ],
  tax_lines: [],
  shipping_lines: [
    {
      id: 186,
      method_title: "Colectare locală",
      method_id: "local_pickup",
      instance_id: "",
      total: "0.00",
      total_tax: "0.00",
      taxes: [],
      meta_data: [],
    },
  ],
  fee_lines: [],
  coupon_lines: [],
  refunds: [],
  payment_url:
    "https://development.cadouribarbati.ro/checkout/order-pay/1088/?pay_for_order=true&key=wc_order_TlgAa4q9PlWcW",
  is_editable: true,
  needs_payment: true,
  needs_processing: true,
  date_created_gmt: "2022-11-26T23:31:05",
  date_modified_gmt: "2022-11-26T23:31:05",
  date_completed_gmt: null,
  date_paid_gmt: null,
  currency_symbol: "lei",
  _links: {
    self: [
      {
        href: "https://development.cadouribarbati.ro/wp-json/wc/v3/orders/1088",
      },
    ],
    collection: [
      {
        href: "https://development.cadouribarbati.ro/wp-json/wc/v3/orders",
      },
    ],
  },
};
